In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, f1_score, recall_score, confusion_matrix
from keras.models import Sequential
from keras.layers import Dense, Dropout

In [2]:
df = pd.read_csv('Churn_treino.csv', sep=';')
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0,1,1,1,10134888,1
1,608,Spain,Female,41,1,8380786,1,0,1,11254258,0
2,502,France,Female,42,8,1596608,3,1,0,11393157,1
3,699,France,Female,39,1,0,2,0,0,9382663,0
4,850,Spain,Female,43,2,12551082,1,1,1,790841,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0,2,1,0,9627064,0
9996,516,France,Male,35,10,5736961,1,1,1,10169977,0
9997,709,France,Female,36,7,0,1,0,1,4208558,1
9998,772,Germany,Male,42,3,7507531,2,1,0,9288852,1
9999,792,France,Female,28,4,13014279,1,1,0,3819078,0

In [3]:
X = df.drop("Exited", axis=1)
y = df["Exited"]

In [4]:
standand_scaler = StandardScaler()
numerical = X.select_dtypes(include=['int64', 'float64']).columns
X[numerical] = standand_scaler.fit_transform(X[numerical])
X

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,-0.326221,France,Female,0.293517,-1.041760,-1.110553,-0.911583,0.646092,0.970243,0.170614
1,-0.440036,Spain,Female,0.198164,-1.387538,0.222782,-0.911583,-1.547768,0.970243,0.353281
2,-1.536794,France,Female,0.293517,1.032908,-0.856542,2.527057,0.646092,-1.030670,0.375948
3,0.501521,France,Female,0.007457,-1.387538,-1.110553,0.807737,-1.547768,-1.030670,0.047859
4,2.063884,Spain,Female,0.388871,-1.041760,0.886252,-0.911583,0.646092,0.970243,-1.354223
...,...,...,...,...,...,...,...,...,...,...
9995,1.246488,France,Male,0.007457,-0.004426,-1.110553,0.807737,0.646092,-1.030670,0.087743
9996,-1.391939,France,Male,-0.373958,1.724464,-0.197835,-0.911583,0.646092,0.970243,0.176340
9997,0.604988,France,Female,-0.278604,0.687130,-1.110553,-0.911583,-1.547768,0.970243,-0.796492
9998,1.256835,Germany,Male,0.293517,-0.695982,0.083852,0.807737,0.646092,-1.030670,0.032551
9999,1.463771,France,Female,-1.041433,-0.350204,0.959944,-0.911583,0.646092,-1.030670,-0.860051

In [6]:
labelencoder = LabelEncoder()
categorical = X.select_dtypes(include=['object']).columns
for col in categorical:
    X[col] = labelencoder.fit_transform(X[col])
X

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,-0.326221,0,0,0.293517,-1.041760,-1.110553,-0.911583,0.646092,0.970243,0.170614
1,-0.440036,2,0,0.198164,-1.387538,0.222782,-0.911583,-1.547768,0.970243,0.353281
2,-1.536794,0,0,0.293517,1.032908,-0.856542,2.527057,0.646092,-1.030670,0.375948
3,0.501521,0,0,0.007457,-1.387538,-1.110553,0.807737,-1.547768,-1.030670,0.047859
4,2.063884,2,0,0.388871,-1.041760,0.886252,-0.911583,0.646092,0.970243,-1.354223
...,...,...,...,...,...,...,...,...,...,...
9995,1.246488,0,1,0.007457,-0.004426,-1.110553,0.807737,0.646092,-1.030670,0.087743
9996,-1.391939,0,1,-0.373958,1.724464,-0.197835,-0.911583,0.646092,0.970243,0.176340
9997,0.604988,0,0,-0.278604,0.687130,-1.110553,-0.911583,-1.547768,0.970243,-0.796492
9998,1.256835,1,1,0.293517,-0.695982,0.083852,0.807737,0.646092,-1.030670,0.032551
9999,1.463771,0,0,-1.041433,-0.350204,0.959944,-0.911583,0.646092,-1.030670,-0.860051

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [8]:
model = Sequential()
model.add(Dense(units=64, activation='relu', input_dim=X_train.shape[1]))
model.add(Dropout(0.4))
model.add(Dense(units=32, activation='relu'))
model.add(Dropout(0.4))
model.add(Dense(units=64, activation='relu'))
model.add(Dropout(0.4))
model.add(Dense(units=1, activation='sigmoid'))

/Users/caio.motta/.pyenv/versions/3.11.11/lib/python3.11/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [9]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=50, batch_size=32)

Epoch 1/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 770us/step - accuracy: 0.7767 - loss: 0.5329
Epoch 2/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 713us/step - accuracy: 0.7959 - loss: 0.4723
Epoch 3/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 713us/step - accuracy: 0.7991 - loss: 0.4614
Epoch 4/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 711us/step - accuracy: 0.8093 - loss: 0.4449
Epoch 5/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 758us/step - accuracy: 0.8268 - loss: 0.4079
Epoch 6/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 687us/step - accuracy: 0.8286 - loss: 0.4104
Epoch 7/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.8296 - loss: 0.4047
Epoch 8/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 708us/step - accuracy: 0.8373 - loss: 0.3874
Epoch 9/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 716us/step - accuracy: 0.8362 - loss: 0.3892
Epoch 10/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 685us/step - accuracy: 0.8396 - loss: 0.3812
Epoch 11/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 697us/step - accuracy: 0.8458 - loss: 0.3752
Epoch 12/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.8411 - loss: 0.3810
Epoch 13/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 703us/step - accuracy: 0.8494 - loss: 0.3717
Epoch 14/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 687us/step - accuracy: 0.8458 - loss: 0.3823
Epoch 15/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 730us/step - accuracy: 0.8374 - loss: 0.3812
Epoch 16/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 709us/step - accuracy: 0.8428 - loss: 0.3791
Epoch 17/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 750us/step - accuracy: 0.8494 - loss: 0.3713
Epoch 18/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 683us/step - accuracy: 0.8457 - loss: 0.3785
Epoch 19/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 684us/step - accuracy: 0.8516 - loss: 0.3698
Epoch 20/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 692us/step - accuracy: 0.8529 - loss: 0.3670
Epoch 21/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 733us/step - accuracy: 0.8482 - loss: 0.3723
Epoch 22/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 693us/step - accuracy: 0.8478 - loss: 0.3629
Epoch 23/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 680us/step - accuracy: 0.8464 - loss: 0.3750
Epoch 24/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 684us/step - accuracy: 0.8434 - loss: 0.3679
Epoch 25/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 709us/step - accuracy: 0.8519 - loss: 0.3575
Epoch 26/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 680us/step - accuracy: 0.8507 - loss: 0.3717
Epoch 27/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 717us/step - accuracy: 0.8492 - loss: 0.3633
Epoch 28/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 717us/step - accuracy: 0.8545 - loss: 0.3617
Epoch 29/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 0.8575 - loss: 0.3644
Epoch 30/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 684us/step - accuracy: 0.8519 - loss: 0.3640
Epoch 31/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 681us/step - accuracy: 0.8610 - loss: 0.3563
Epoch 32/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 698us/step - accuracy: 0.8538 - loss: 0.3643
Epoch 33/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 706us/step - accuracy: 0.8552 - loss: 0.3631
Epoch 34/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 707us/step - accuracy: 0.8510 - loss: 0.3688
Epoch 35/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 665us/step - accuracy: 0.8578 - loss: 0.3529
Epoch 36/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 683us/step - accuracy: 0.8511 - loss: 0.3625
Epoch 37/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 680us/step - accuracy: 0.8559 - loss: 0.3604
Epoch 38/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 755us/step - accuracy: 0.8561 - loss: 0.3673
Epoch 39/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 689us/step - accuracy: 0.8528 - loss: 0.3610
Epoch 40/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 701us/step - accuracy: 0.8529 - loss: 0.3573
Epoch 41/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 752us/step - accuracy: 0.8483 - loss: 0.3635
Epoch 42/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 685us/step - accuracy: 0.8551 - loss: 0.3533
Epoch 43/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 663us/step - accuracy: 0.8534 - loss: 0.3537
Epoch 44/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 663us/step - accuracy: 0.8574 - loss: 0.3476
Epoch 45/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 743us/step - accuracy: 0.8594 - loss: 0.3422
Epoch 46/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 674us/step - accuracy: 0.8556 - loss: 0.3535
Epoch 47/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 965us/step - accuracy: 0.8599 - loss: 0.3573
Epoch 48/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 682us/step - accuracy: 0.8595 - loss: 0.3470
Epoch 49/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 715us/step - accuracy: 0.8621 - loss: 0.3499
Epoch 50/50
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 677us/step - accuracy: 0.8541 - loss: 0.3530

In [10]:
prediction = model.predict(X_test)
prediction

94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 682us/step

array([[0.25505942],
       [0.26814026],
       [0.16212966],
       ...,
       [0.08653329],
       [0.09967122],
       [0.5806562 ]], dtype=float32)

In [11]:
y_pred = (prediction > 0.5).astype('int32')
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [1]], dtype=int32)

In [12]:
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print(f'F1: {f1}')
print(f'Recall: {recall}')
print(f'Confusion Matrix: {confusion}')

Accuracy: 0.859
F1: 0.590513068731849
Recall: 0.49114331723027377
Confusion Matrix: [[2272  107]
 [ 316  305]]