In [11]:
import h2o
from h2o.automl import H2OAutoML

In [12]:
h2o.init(ip="localhost", port="8080")

Checking whether there is an H2O instance running at http://localhost:8080. connected.
Warning: Your H2O cluster version is (1 year, 9 months and 23 days) old.  There may be a newer version available.
Please download and install the latest version from: https://h2o-release.s3.amazonaws.com/h2o/latest_stable.html

--------------------------  ---------------------------------
H2O_cluster_uptime:         18 mins 49 secs
H2O_cluster_timezone:       America/Sao_Paulo
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.40.0.4
H2O_cluster_version_age:    1 year, 9 months and 23 days
H2O_cluster_name:           H2O_from_python_caio_motta_asf0qh
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    3.204 Gb
H2O_cluster_total_cores:    8
H2O_cluster_allowed_cores:  8
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://localhost:8080
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
Python_version:             3.11.11 final
--------------------------  ---------------------------------

In [13]:
data = h2o.import_file("insurance.csv")

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

In [14]:
data

  C1  GoodStudent    Age         SocioEcon    RiskAversion    VehicleYear    ThisCarDam    RuggedAuto    Accident    MakeModel    DrivQuality    Mileage     Antilock    DrivingSkill    SeniorTrain    ThisCarCost    Theft    CarValue    HomeBase    AntiTheft    PropCost     OtherCarCost    OtherCar    MedCost    Cushioning    Airbag    ILiCost    DrivHist
----  -------------  ----------  -----------  --------------  -------------  ------------  ------------  ----------  -----------  -------------  ----------  ----------  --------------  -------------  -------------  -------  ----------  ----------  -----------  -----------  --------------  ----------  ---------  ------------  --------  ---------  ----------
   1  False          Adult       Prole        Adventurous     Older          Moderate      EggShell      Mild        Economy      Poor           TwentyThou  False       SubStandard     False          TenThou        False    FiveThou    City        False        TenThou      Thousand        True        Thousand   Poor          False     Thousand   Many
   2  False          Senior      Prole        Cautious        Current        None          Football      None        Economy      Normal         TwentyThou  False       Normal          True           Thousand       False    TenThou     City        True         Thousand     Thousand        True        Thousand   Good          True      Thousand   Zero
   3  False          Senior      UpperMiddle  Psychopath      Current        None          Football      None        FamilySedan  Excellent      Domino      True        Normal          False          Thousand       False    TwentyThou  City        False        Thousand     Thousand        False       Thousand   Good          True      Thousand   One
   4  False          Adolescent  Middle       Normal          Older          None          EggShell      None        Economy      Normal         FiftyThou   False       Normal          False          Thousand       False    FiveThou    Suburb      False        Thousand     Thousand        True        Thousand   Fair          False     Thousand   Zero
   5  False          Adolescent  Prole        Normal          Older          Moderate      Football      Moderate    Economy      Poor           FiftyThou   False       SubStandard     False          TenThou        False    FiveThou    City        False        TenThou      Thousand        False       Thousand   Fair          False     Thousand   Many
   6  False          Adult       UpperMiddle  Normal          Current        Moderate      EggShell      Moderate    SportsCar    Poor           FiftyThou   True        SubStandard     False          HundredThou    False    TwentyThou  Suburb      True         HundredThou  HundredThou     True        TenThou    Poor          True      Thousand   Many
   7  False          Senior      UpperMiddle  Normal          Current        Mild          Football      Mild        Economy      Poor           FiveThou    False       SubStandard     False          TenThou        False    TenThou     Secure      True         TenThou      Thousand        False       Thousand   Excellent     True      Thousand   Many
   8  False          Adult       Prole        Normal          Older          Severe        EggShell      Severe      Economy      Poor           TwentyThou  False       SubStandard     False          TenThou        False    TenThou     City        False        Million      HundredThou     True        Thousand   Fair          False     Thousand   Many
   9  False          Adult       Prole        Normal          Older          Severe        EggShell      Severe      Economy      Poor           TwentyThou  False       SubStandard     False          TenThou        False    FiveThou    City        False        HundredThou  TenThou         False       TenThou    Poor          False     Thousand   Many
  10  True           Adolescent  Prole        Cautious        Older          Severe        Football      Severe      FamilySedan  Poor           TwentyThou  False       SubStandard     False          TenThou        False    FiveThou    City        True         HundredThou  HundredThou     True        Thousand   Good          False     Thousand   Many
[20000 rows x 28 columns]

In [15]:
data = data.drop("C1")

In [16]:
data

GoodStudent    Age         SocioEcon    RiskAversion    VehicleYear    ThisCarDam    RuggedAuto    Accident    MakeModel    DrivQuality    Mileage     Antilock    DrivingSkill    SeniorTrain    ThisCarCost    Theft    CarValue    HomeBase    AntiTheft    PropCost     OtherCarCost    OtherCar    MedCost    Cushioning    Airbag    ILiCost    DrivHist
-------------  ----------  -----------  --------------  -------------  ------------  ------------  ----------  -----------  -------------  ----------  ----------  --------------  -------------  -------------  -------  ----------  ----------  -----------  -----------  --------------  ----------  ---------  ------------  --------  ---------  ----------
False          Adult       Prole        Adventurous     Older          Moderate      EggShell      Mild        Economy      Poor           TwentyThou  False       SubStandard     False          TenThou        False    FiveThou    City        False        TenThou      Thousand        True        Thousand   Poor          False     Thousand   Many
False          Senior      Prole        Cautious        Current        None          Football      None        Economy      Normal         TwentyThou  False       Normal          True           Thousand       False    TenThou     City        True         Thousand     Thousand        True        Thousand   Good          True      Thousand   Zero
False          Senior      UpperMiddle  Psychopath      Current        None          Football      None        FamilySedan  Excellent      Domino      True        Normal          False          Thousand       False    TwentyThou  City        False        Thousand     Thousand        False       Thousand   Good          True      Thousand   One
False          Adolescent  Middle       Normal          Older          None          EggShell      None        Economy      Normal         FiftyThou   False       Normal          False          Thousand       False    FiveThou    Suburb      False        Thousand     Thousand        True        Thousand   Fair          False     Thousand   Zero
False          Adolescent  Prole        Normal          Older          Moderate      Football      Moderate    Economy      Poor           FiftyThou   False       SubStandard     False          TenThou        False    FiveThou    City        False        TenThou      Thousand        False       Thousand   Fair          False     Thousand   Many
False          Adult       UpperMiddle  Normal          Current        Moderate      EggShell      Moderate    SportsCar    Poor           FiftyThou   True        SubStandard     False          HundredThou    False    TwentyThou  Suburb      True         HundredThou  HundredThou     True        TenThou    Poor          True      Thousand   Many
False          Senior      UpperMiddle  Normal          Current        Mild          Football      Mild        Economy      Poor           FiveThou    False       SubStandard     False          TenThou        False    TenThou     Secure      True         TenThou      Thousand        False       Thousand   Excellent     True      Thousand   Many
False          Adult       Prole        Normal          Older          Severe        EggShell      Severe      Economy      Poor           TwentyThou  False       SubStandard     False          TenThou        False    TenThou     City        False        Million      HundredThou     True        Thousand   Fair          False     Thousand   Many
False          Adult       Prole        Normal          Older          Severe        EggShell      Severe      Economy      Poor           TwentyThou  False       SubStandard     False          TenThou        False    FiveThou    City        False        HundredThou  TenThou         False       TenThou    Poor          False     Thousand   Many
True           Adolescent  Prole        Cautious        Older          Severe        Football      Severe      FamilySedan  Poor           TwentyThou  False       SubStandard     False          TenThou        False    FiveThou    City        True         HundredThou  HundredThou     True        Thousand   Good          False     Thousand   Many
[20000 rows x 27 columns]

In [17]:
train, test = data.split_frame(ratios=[0.7], seed=0)

In [18]:
train

GoodStudent    Age         SocioEcon    RiskAversion    VehicleYear    ThisCarDam    RuggedAuto    Accident    MakeModel    DrivQuality    Mileage     Antilock    DrivingSkill    SeniorTrain    ThisCarCost    Theft    CarValue    HomeBase    AntiTheft    PropCost     OtherCarCost    OtherCar    MedCost    Cushioning    Airbag    ILiCost    DrivHist
-------------  ----------  -----------  --------------  -------------  ------------  ------------  ----------  -----------  -------------  ----------  ----------  --------------  -------------  -------------  -------  ----------  ----------  -----------  -----------  --------------  ----------  ---------  ------------  --------  ---------  ----------
False          Adult       Prole        Adventurous     Older          Moderate      EggShell      Mild        Economy      Poor           TwentyThou  False       SubStandard     False          TenThou        False    FiveThou    City        False        TenThou      Thousand        True        Thousand   Poor          False     Thousand   Many
False          Senior      Prole        Cautious        Current        None          Football      None        Economy      Normal         TwentyThou  False       Normal          True           Thousand       False    TenThou     City        True         Thousand     Thousand        True        Thousand   Good          True      Thousand   Zero
False          Senior      UpperMiddle  Psychopath      Current        None          Football      None        FamilySedan  Excellent      Domino      True        Normal          False          Thousand       False    TwentyThou  City        False        Thousand     Thousand        False       Thousand   Good          True      Thousand   One
False          Adolescent  Prole        Normal          Older          Moderate      Football      Moderate    Economy      Poor           FiftyThou   False       SubStandard     False          TenThou        False    FiveThou    City        False        TenThou      Thousand        False       Thousand   Fair          False     Thousand   Many
False          Senior      UpperMiddle  Normal          Current        Mild          Football      Mild        Economy      Poor           FiveThou    False       SubStandard     False          TenThou        False    TenThou     Secure      True         TenThou      Thousand        False       Thousand   Excellent     True      Thousand   Many
False          Adult       Prole        Normal          Older          Severe        EggShell      Severe      Economy      Poor           TwentyThou  False       SubStandard     False          TenThou        False    FiveThou    City        False        HundredThou  TenThou         False       TenThou    Poor          False     Thousand   Many
True           Adolescent  Prole        Cautious        Older          Severe        Football      Severe      FamilySedan  Poor           TwentyThou  False       SubStandard     False          TenThou        False    FiveThou    City        True         HundredThou  HundredThou     True        Thousand   Good          False     Thousand   Many
False          Adult       Prole        Normal          Older          None          Tank          None        FamilySedan  Normal         TwentyThou  False       Normal          False          Thousand       False    TenThou     City        False        Thousand     Thousand        False       Thousand   Excellent     True      Thousand   One
False          Adult       Middle       Normal          Older          None          Football      Mild        FamilySedan  Poor           FiftyThou   False       SubStandard     False          Thousand       False    TwentyThou  Suburb      False        Thousand     Thousand        True        Thousand   Good          False     Thousand   Many
False          Adult       Middle       Cautious        Current        None          Football      None        FamilySedan  Normal         TwentyThou  False       Normal          False          Thousand       False    TwentyThou  Secure      True         Thousand     Thousand        True        Thousand   Excellent     True      Thousand   Zero
[14064 rows x 27 columns]

In [19]:
model_automl = H2OAutoML(max_runtime_secs=180, seed=0, sort_metric="AUTO")
model_automl.train(y="Accident", training_frame=train)

AutoML progress: |█████████████
19:23:11.238: GLM_1_AutoML_2_20250220_192234 [GLM def_1] failed: java.lang.ArrayIndexOutOfBoundsException: 83

██████████████████████████████████████████████████| (done) 100%

Model Details
=============
H2OStackedEnsembleEstimator : Stacked Ensemble
Model Key: StackedEnsemble_AllModels_1_AutoML_2_20250220_192234


Model Summary for Stacked Ensemble:
key                                   value
------------------------------------  ----------------
Stacking strategy                     cross_validation
Number of base models (used / total)  7/7
# GBM base models (used / total)      4/4
# XGBoost base models (used / total)  2/2
# DRF base models (used / total)      1/1
Metalearner algorithm                 GLM
Metalearner fold assignment scheme    Random
Metalearner nfolds                    5
Metalearner fold_column
Custom metalearner hyperparameters    None

ModelMetricsMultinomialGLM: stackedensemble
** Reported on train data. **

MSE: 0.025961178970386096
RMSE: 0.16112473109484496
LogLoss: 0.08980421148402264
Null degrees of freedom: 10035
Residual degrees of freedom: 9991
Null deviance: 18157.796428917954
Residual deviance: 1802.5501329073024
AUC table was not computed: it is either disabled (model parameter 'auc_type' was set to AUTO or NONE) or the domain size exceeds the limit (maximum is 50 domains).
AUCPR table was not computed: it is either disabled (model parameter 'auc_type' was set to AUTO or NONE) or the domain size exceeds the limit (maximum is 50 domains).

Confusion Matrix: Row labels: Actual class; Column labels: Predicted class
Mild    Moderate    None    Severe    Error        Rate
------  ----------  ------  --------  -----------  ------------
679     38          123     2         0.193587     163 / 842
30      656         2       124       0.192118     156 / 812
2       0           7181    0         0.000278435  2 / 7,183
0       11          0       1188      0.00917431   11 / 1,199
711     705         7306    1314      0.0330809    332 / 10,036

Top-4 Hit Ratios:
k    hit_ratio
---  -----------
1    0.966919
2    0.999203
3    1
4    1

ModelMetricsMultinomialGLM: stackedensemble
** Reported on cross-validation data. **

MSE: 0.03948127573697014
RMSE: 0.19869895756387385
LogLoss: 0.13562497239306728
Null degrees of freedom: 14063
Residual degrees of freedom: 14027
Null deviance: 25519.598229520714
Residual deviance: 3814.859223472196
AUC table was not computed: it is either disabled (model parameter 'auc_type' was set to AUTO or NONE) or the domain size exceeds the limit (maximum is 50 domains).
AUCPR table was not computed: it is either disabled (model parameter 'auc_type' was set to AUTO or NONE) or the domain size exceeds the limit (maximum is 50 domains).

Confusion Matrix: Row labels: Actual class; Column labels: Predicted class
Mild    Moderate    None    Severe    Error       Rate
------  ----------  ------  --------  ----------  ------------
933     96          190     3         0.236498    289 / 1,222
63      846         3       216       0.25        282 / 1,128
35      0           10017   0         0.00348189  35 / 10,052
0       94          0       1568      0.0565584   94 / 1,662
1031    1036        10210   1787      0.0497725   700 / 14,064

Top-4 Hit Ratios:
k    hit_ratio
---  -----------
1    0.950228
2    0.998791
3    0.999787
4    1

Cross-Validation Metrics Summary:
                         mean       sd          cv_1_valid    cv_2_valid    cv_3_valid    cv_4_valid    cv_5_valid
-----------------------  ---------  ----------  ------------  ------------  ------------  ------------  ------------
accuracy                 0.950225   0.00386527  0.945302      0.948355      0.952597      0.955319      0.949555
auc                      nan        0           nan           nan           nan           nan           nan
err                      0.0497745  0.00386527  0.0546985     0.0516449     0.0474033     0.0446809     0.0504451
err_count                140        11.4018     156           146           136           126           136
logloss                  0.1356     0.00529621  0.142293      0.139621      0.129388      0.134467      0.13223
max_per_class_error      0.25549    0.0185651   0.276151      0.268868      0.243802      0.230415      0.258216
mean_per_class_accuracy  0.863296   0.0115999   0.852144      0.854609      0.875507      0.876059      0.858159
mean_per_class_error     0.136704   0.0115999   0.147856      0.145391      0.124493      0.123941      0.141841
mse                      0.0394738  0.00192445  0.0417934     0.0412836     0.0377839     0.0378499     0.0386583
null_deviance            5103.92    176.51      5273.35       5149.33       5241.08       5008.8        4847.03
pr_auc                   nan        0           nan           nan           nan           nan           nan
r2                       0.925131   0.00309929  0.921012      0.923947      0.928927      0.927386      0.924383
residual_deviance        762.972    38.7614     811.639       789.418       742.427       758.393       712.983
rmse                     0.198633   0.00482641  0.204434      0.203184      0.194381      0.19455       0.196617

[tips]
Use `model.explain()` to inspect the model.
--
Use `h2o.display.toggle_user_tips()` to switch on/off this section.

In [20]:
ranking = model_automl.leaderboard
ranking = ranking.as_data_frame()
ranking

,model_id,mean_per_class_error,logloss,rmse,mse
0,StackedEnsemble_AllModels_1_AutoML_2_20250220_...,0.136634,0.135625,0.198699,0.039481
1,StackedEnsemble_BestOfFamily_2_AutoML_2_202502...,0.139477,0.138253,0.200047,0.040019
2,GBM_3_AutoML_2_20250220_192234,0.140044,0.141504,0.200169,0.040067
3,GBM_2_AutoML_2_20250220_192234,0.140356,0.137282,0.198190,0.039279
4,StackedEnsemble_BestOfFamily_1_AutoML_2_202502...,0.141271,0.133427,0.196844,0.038748
5,GBM_1_AutoML_2_20250220_192234,0.141632,0.133520,0.195896,0.038375
6,XGBoost_2_AutoML_2_20250220_192234,0.141922,0.140219,0.199958,0.039983
7,GBM_4_AutoML_2_20250220_192234,0.142399,0.148054,0.203097,0.041249
8,DRF_1_AutoML_2_20250220_192234,0.142627,0.189437,0.202530,0.041018
9,XGBoost_1_AutoML_2_20250220_192234,0.144857,0.138923,0.200021,0.040008

In [21]:
predict = model_automl.leader.predict(test)
predict

stackedensemble prediction progress: |███████████████████████████████████████████| (done) 100%

predict          Mild     Moderate         None       Severe
---------  ----------  -----------  -----------  -----------
None       0.00156361  9.57417e-05  0.998306     3.42879e-05
Moderate   0.0126327   0.960344     0.000930389  0.0260928
Severe     0.0036007   0.0666459    0.000818844  0.928935
None       0.00200092  0.000130105  0.997819     4.99336e-05
Severe     0.0206163   0.330415     0.00436979   0.644599
None       0.0106849   0.000588278  0.988521     0.000206061
Mild       0.951337    0.0371217    0.00881306   0.00272854
None       0.0012476   9.11142e-05  0.99863      3.10067e-05
None       0.00210671  0.000138007  0.997704     5.16429e-05
Severe     0.00599458  0.137955     0.00131394   0.854736
[5936 rows x 5 columns]